# Generated by Django 5.0.6 on 2024-07-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Founders',
        ),
    ]
